spring: 
  profiles:
    active: 
      - dev 
    
spring:  #开发环境
  profiles: dev
  application: microservicecloud-config-sun-dev
      
spring:  #测试环境
  profiles:  test
  application: microservicecloud-config-sun-test